// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231214094305_InsertSeedData")]
    partial class InsertSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.MockEntities.MockSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaybookExecutorsPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaybooksPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MockSessions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb0f9f1b-8d36-4fe1-88eb-194a4b7129fb"),
                            IP = "10.84.9.169",
                            InventoryPath = "/etc/ansible/inventory/",
                            Password = "TurnThat62To125!",
                            PlaybookExecutorsPath = "/etc/ansible/playbooks/playbookExecutors/",
                            PlaybooksPath = "/etc/ansible/playbooks/",
                            Username = "mihairaducu"
                        });
                });

            modelBuilder.Entity("Domain.Entities.NetworkDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NetworkDevices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            HostName = "lro9999-nwprsw-p001.9999.ro.lidl",
                            IP = "197.120.24.132",
                            Location = "HQ",
                            OS = "HuaweiOS",
                            OSVersion = "1.0",
                            Vendor = "Huawei"
                        },
                        new
                        {
                            Id = new Guid("6313179f-7837-473a-a4d5-a5571b43e6a6"),
                            HostName = "lro9999-nwprsw-p002.9999.ro.lidl",
                            IP = "197.120.24.133",
                            Location = "HQ",
                            OS = "HuaweiOS",
                            OSVersion = "1.0",
                            Vendor = "Huawei"
                        },
                        new
                        {
                            Id = new Guid("bf3f3002-7e53-441e-8b76-f6280be284aa"),
                            HostName = "lro09989-nwwavpn-p011.09989.ro.lidl",
                            IP = "197.120.24.18",
                            Location = "Store9999",
                            OS = "IOS",
                            OSVersion = "17.05.03a",
                            Vendor = "Cisco"
                        },
                        new
                        {
                            Id = new Guid("bf3f3002-7e53-441e-8b76-f6280be284ab"),
                            HostName = "lro09989-nwwavpn-p012.09989.ro.lidl",
                            IP = "197.120.24.19",
                            Location = "Store9999",
                            OS = "IOS",
                            OSVersion = "17.05.03a",
                            Vendor = "Cisco"
                        },
                        new
                        {
                            Id = new Guid("bf3f3002-7e53-441e-8b76-f6280be284ac"),
                            HostName = "lro09989-fwint-p01a.09989.ro.lidl",
                            IP = "197.120.24.22",
                            Location = "Store9999",
                            OS = "FortinetOS",
                            OSVersion = "1.2",
                            Vendor = "Fortinet"
                        },
                        new
                        {
                            Id = new Guid("bf3f3002-7e53-441e-8b76-f6280be284ad"),
                            HostName = "lro09989-fwint-p01b.09989.ro.lidl",
                            IP = "197.120.24.23",
                            Location = "Store9999",
                            OS = "FortinetOS",
                            OSVersion = "1.2",
                            Vendor = "Fortinet"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe98f549-e790-4e9f-aa16-18c2292a2ee9"),
                            Department = "IT",
                            Location = "HQ",
                            LocationId = 1,
                            Password = "password",
                            UserName = "raducuadm"
                        },
                        new
                        {
                            Id = new Guid("fe98f549-e790-4e9f-aa16-18c2292a2eff"),
                            Department = "Tehnic",
                            Location = "Iernut",
                            LocationId = 6,
                            Password = "passwordadm",
                            UserName = "testuser"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
